apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-us-west-2b
provisioner: kubernetes.io/aws-ebs
parameters:
  type: io1
  iopsPerGB: "10"
  fsType: ext4
  zone: us-west-2b
volumeBindingMode: WaitForFirstConsumer
